//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientRegisterUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoritesCompositions
    {
        public long id { get; set; }
        public Nullable<long> id_products { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
