//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientRegisterUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public long id { get; set; }
        public Nullable<long> id_user { get; set; }
        public byte[] picture_profile { get; set; }
        public string description { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
